# GitHub Actions CI/CD Pipeline

name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md" # Ignore README.md changes to avoid triggering the workflow unnecessarily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use Node.js version 20

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests with MongoDB URI from GitHub Secrets
      - name: Run tests
        env:
          MONGODB_TEST_URI: ${{ secrets.MONGODB_TEST_URI }} # Use MongoDB URI from secrets
        run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 2: Login to Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Build and push Docker image to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile # Specify the Dockerfile to use
          push: true # Push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/crypto-trade-backend-app:${{ github.run_id }} # Tag the image with the run ID
