# GitHub Actions CI/CD Pipeline

name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md" # Ignore README.md changes to avoid triggering the workflow unnecessarily
      - "helm/**" # Ignore helm changes to avoid triggering the workflow unnecessarily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use Node.js version 20

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests with MongoDB URI from GitHub Secrets
      - name: Run tests
        env:
          MONGODB_TEST_URI: ${{ secrets.MONGODB_TEST_URI }} # Use MongoDB URI from secrets
        run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 2: Login to Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Build and push Docker image to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile # Specify the Dockerfile to use
          push: true # Push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/crypto-trade-backend-app:${{ github.run_id }} # Tag the image with the run ID

  # GitHub Actions Workflow to update the image tag in Helm values.yaml
  update-image-tag-in-helm-values:
    runs-on: ubuntu-latest # Specifies the operating system for the job

    needs: docker # Indicates that this job depends on the successful completion of the 'docker' job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }} # Uses a secret token for accessing the repository

      - name: Update image tag in Helm chart
        # Use sed to update the image tag in the Helm values.yaml file with the GitHub run ID
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/crypto-trade-backend-app/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "pranayreddy.k12@gmail.com"
          git config --global user.name "PranayReddy-K"

          git add helm/crypto-trade-backend-app/values.yaml

          git commit -m "feat: Update image tag in Helm chart to GitHub run ID ${{ github.run_id }}"

          git push
